export enum ConjugatedForm {
    Adverbial,
    Causative,
    CausativePassive,
    ClassicalPlainForm,
    Conditional,
    Contracted,
    TaraConditional,
    ConditionalContraction,
    Continuative,
    IndeclinableNominal,
    IrrealisNuForm,
    IrrealisUForm,
    GaruForm,
    GozaiForm,
    Imperative,
    NaiForm,
    Passive,
    PastForm,
    PlainForm,
    PoliteForm,
    Potential, // TODO
    TeForm,
    Volitional,
    Unknown,
}