export enum ConjugatedForm {
    ClassicalPlainForm,
    Conditional,
    ConditionalContraction,
    Continuative,
    IndeclinableNominal,
    GaruForm,
    GozaiForm,
    Irrealis,
    Imperative,
    PlainForm,
    TaConjunction,
    TeConjunction,
    Unknown,
}